// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "../src/CumulativeMerkleDistributor.sol";
import "../src/MockERC20.sol";

/**
 * Proves the JS Merkle builder (biliquid-be/src/api/merkle-snapshot/services/merkle-tree.js)
 * produces roots + proofs that the on-chain contract accepts. The root/proofs below were
 * generated by that builder for a fixed 4-account fixture (see test scaffolding in the PR).
 */
contract CumulativeMerkleDistributorTest is Test {
    CumulativeMerkleDistributor dist;
    MockERC20 usdc;

    // Fixture from merkle-tree.js buildCumulativeTree(...)
    bytes32 constant ROOT = 0xd66a98c0f07d5012c85c04c1ba18b20fb73e0338086894775cff50dcb5df8c04;

    address constant A = 0x70997970C51812dc3A010C7d01b50e0d17dc79C8; // 3.0 USDC
    address constant B = 0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC; // 4.5
    address constant C = 0x90F79bf6EB2c4f870365E785982E1f101E93b906; // 1.5
    address constant D = 0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65; // 9.99

    function setUp() public {
        usdc = new MockERC20("USD Coin", "USDC", 6);
        dist = new CumulativeMerkleDistributor(address(usdc));
        usdc.mint(address(dist), 100_000_000); // 100 USDC funded
        dist.setMerkleRoot(ROOT);
    }

    function _proofB() internal pure returns (bytes32[] memory p) {
        p = new bytes32[](2);
        p[0] = 0xc02a132a033cebdaeab33e069ddab81e67d9c1ee4caa7ac08b850866215421b0;
        p[1] = 0x6b5b7a4c866beca4e3505ec2fc30a5e4f08dc7ce3ff34feb7b9c5002ac6530c1;
    }

    function _proofA() internal pure returns (bytes32[] memory p) {
        p = new bytes32[](2);
        p[0] = 0xceff9a1ecfdba421243adbad5deea2de81c9d82d70322f952635f833f7377452;
        p[1] = 0x7ce8fd91655feb8ef43134ce29b4e39b53597907c90352afde6e3f6b3dd6a7ec;
    }

    function test_ClaimValidProof() public {
        assertEq(usdc.balanceOf(B), 0);
        dist.claim(B, 4_500_000, ROOT, _proofB());
        assertEq(usdc.balanceOf(B), 4_500_000, "B receives 4.5 USDC");
        assertEq(dist.cumulativeClaimed(B), 4_500_000);
    }

    function test_ClaimTwiceNothingToClaim() public {
        dist.claim(B, 4_500_000, ROOT, _proofB());
        vm.expectRevert(CumulativeMerkleDistributor.NothingToClaim.selector);
        dist.claim(B, 4_500_000, ROOT, _proofB());
    }

    function test_ClaimPaysOnlyDeltaAfterRootBump() public {
        dist.claim(B, 4_500_000, ROOT, _proofB());
        assertEq(usdc.balanceOf(B), 4_500_000);

        // New root where B's cumulative grew to 6.0 USDC; proof recomputed by builder.
        bytes32 newRoot = 0x0; // set below via helper root+proof
        // Use a second fixture: single-leaf tree for B at 6,000,000 → root == leaf, proof == []
        bytes32 leafB6 = keccak256(abi.encodePacked(B, uint256(6_000_000)));
        newRoot = leafB6;
        dist.setMerkleRoot(newRoot);
        bytes32[] memory empty = new bytes32[](0);
        dist.claim(B, 6_000_000, newRoot, empty);
        assertEq(usdc.balanceOf(B), 6_000_000, "B now has 6.0 total (paid 1.5 delta)");
        assertEq(dist.cumulativeClaimed(B), 6_000_000);
    }

    function test_ClaimWrongAmountReverts() public {
        vm.expectRevert(CumulativeMerkleDistributor.InvalidProof.selector);
        dist.claim(B, 4_500_001, ROOT, _proofB()); // amount not in tree
    }

    function test_ClaimStaleRootReverts() public {
        bytes32[] memory p = _proofB();
        vm.expectRevert(CumulativeMerkleDistributor.MerkleRootWasUpdated.selector);
        dist.claim(B, 4_500_000, bytes32(uint256(1)), p);
    }

    function test_ClaimForA() public {
        dist.claim(A, 3_000_000, ROOT, _proofA());
        assertEq(usdc.balanceOf(A), 3_000_000);
    }

    function test_OnlyOwnerSetRoot() public {
        vm.prank(address(0xBEEF));
        vm.expectRevert();
        dist.setMerkleRoot(bytes32(uint256(2)));
    }
}
